$(document).ready(function(){
    $("#layout-menu-side-bar").mouseenter(function(){
        $("#layout-menu-background-right").addClass("layout-menu-background-right-open");
        $("#layout-menu-background-right").removeClass("layout-menu-background-right-close");
    }).mouseleave(function(){
        $("#layout-menu-background-right").removeClass("layout-menu-background-right-open");
        $("#layout-menu-background-right").addClass("layout-menu-background-right-close");
    });
});